# This is a basic workflow to help you get started with Actions

name: Install Pop!_OS LEMP setup

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run install script
        run: DONT_SECURE_INSTALL_MYSQL=yes /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/raikasdev/pop-lemp-setup/master/install.sh)"
      - name: Curl
        run: curl -f http://localhost:80
      - name: Setup MySQL
        run: |
          echo "ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';\nFLUSH PRIVILEGES;" > setup.sql
          sudo mysql < "setup.sql"
      - name: Install Dudestack # Using raikasdev/dudestack for Pop!_OS support
        run: |
          git clone https://github.com/raikasdev/dudestack
          sudo ln -s "$(realpath ./dudestack/bin/popos.sh)" /usr/local/bin/createproject
      - name: Restart php7.4
        run: sudo systemctl status php7.4-fpm
      - name: Create project using dudestack
        run: echo -e "airdev\nroot\ntestuser\ntestpassword\ntest@example.com\nn" | createproject
      - name: Curl project
        run: curl -f https://airdev.test
      - name: Install air-light # Using raikasdev/air-light for Pop!_OS support
        run: |
          git clone -b pop-os-support https://github.com/raikasdev/air-light
          sudo ln -s "$(realpath ./air-light/bin/newtheme-popos.sh)" /usr/local/bin/newtheme
      - name: Create theme using air-light
        run: echo -e "y\nairdev\nairdev" | newtheme
      - name: Curl project
        run: curl -f https://airdev.test
      - name: Curl project theme style.css
        run: curl -f https://airdev.test/content/themes/airdev/style.css
